<a href="https://colab.research.google.com/github/rautaditya2606/deep-learning-cv-by-jovian/blob/main/Zero_to_GANs_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [340]:
import torch
from torch.utils.data import TensorDataset, DataLoader # data handler
import torch.nn.functional as f # loss

from torch import nn

In [141]:
t1 = torch.tensor(3.)
t1, t1.dtype

(tensor(3.), torch.float32)

In [142]:
t2 = torch.tensor([[[1.,2.,3.],
                    [4.,5.,6.],
                    [7.,8.,9.]]])

In [143]:
t2, t2.dtype

(tensor([[[1., 2., 3.],
          [4., 5., 6.],
          [7., 8., 9.]]]),
 torch.float32)

In [144]:
t2.shape

torch.Size([1, 3, 3])

In [145]:
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)

In [146]:
y = w * x + b
y

tensor(17., grad_fn=<AddBackward0>)

In [147]:
# computes derivatives
y.backward()

In [148]:
#display derivatives
print('dy/dx', x.grad)
print('dy/dw', w.grad)
print('dy/db', b.grad)

dy/dx None
dy/dw tensor(3.)
dy/db tensor(1.)


In [149]:
t6 = torch.full([1,3,3], 18)
t6

tensor([[[18, 18, 18],
         [18, 18, 18],
         [18, 18, 18]]])

In [150]:
t7 = torch.cat((t2, t6))
t7, t7.shape

(tensor([[[ 1.,  2.,  3.],
          [ 4.,  5.,  6.],
          [ 7.,  8.,  9.]],
 
         [[18., 18., 18.],
          [18., 18., 18.],
          [18., 18., 18.]]]),
 torch.Size([2, 3, 3]))

In [151]:
t8 = torch.sin(t7)
t8

tensor([[[ 0.8415,  0.9093,  0.1411],
         [-0.7568, -0.9589, -0.2794],
         [ 0.6570,  0.9894,  0.4121]],

        [[-0.7510, -0.7510, -0.7510],
         [-0.7510, -0.7510, -0.7510],
         [-0.7510, -0.7510, -0.7510]]])

In [152]:
t9 = t7.reshape(3,3,2)
t9

tensor([[[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.]],

        [[ 7.,  8.],
         [ 9., 18.],
         [18., 18.]],

        [[18., 18.],
         [18., 18.],
         [18., 18.]]])

In [153]:
# integration of numpy and pytorch

In [154]:
import numpy as np

x = np.array([[1.,2.],
              [3.,4.]])
x, x.dtype

(array([[1., 2.],
        [3., 4.]]),
 dtype('float64'))

In [155]:
y = torch.from_numpy(x).type(torch.float32)
y, y.dtype

(tensor([[1., 2.],
         [3., 4.]]),
 torch.float32)

In [156]:
# linear regression model

In [157]:
# inputs (temp, rainfall ,humidity)
num_inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70]])

In [158]:
num_targets = np.array([[56,70],
                    [81,101],
                    [119, 133],
                    [22, 37],
                    [103, 119]], dtype='float32')

In [189]:
# convert np array to torch tensor
inputs = torch.from_numpy(num_inputs)
targets = torch.from_numpy(num_targets)

In [190]:
inputs = inputs.type(torch.float32)
targets = targets.type(torch.float32)

In [191]:
w = torch.randn(2, 3, requires_grad=True)
b = torch.randn(2, requires_grad = True)
w, b

(tensor([[ 0.9097, -0.0416,  0.4657],
         [-1.4288,  0.9336, -0.8311]], requires_grad=True),
 tensor([1.1280, 0.6053], requires_grad=True))

In [192]:
inputs

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])

In [193]:
inputs @ w.T + b

tensor([[  84.7705,  -76.8813],
        [ 110.0502, -100.4466],
        [ 101.7019,  -46.7980],
        [ 109.3565, -135.7370],
        [  92.4982,  -66.5305]], grad_fn=<AddBackward0>)

In [194]:
def model(x):
  return x @ w.T + b

In [195]:
preds = model(inputs)
preds

tensor([[  84.7705,  -76.8813],
        [ 110.0502, -100.4466],
        [ 101.7019,  -46.7980],
        [ 109.3565, -135.7370],
        [  92.4982,  -66.5305]], grad_fn=<AddBackward0>)

In [196]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [197]:
def mse(preds, targets):
  diff = preds - targets
  return torch.sum(diff * diff) / diff.numel()

In [198]:
loss = mse(preds, targets)

In [199]:
# compute gradient
loss.backward()

In [200]:
w, w.grad

(tensor([[ 0.9097, -0.0416,  0.4657],
         [-1.4288,  0.9336, -0.8311]], requires_grad=True),
 tensor([[  2284.9226,    982.8491,    918.0232],
         [-15023.4365, -15379.9805,  -9803.0342]]))

In [201]:
b, b.grad

(tensor([1.1280, 0.6053], requires_grad=True), tensor([  23.4754, -177.2787]))

In [217]:
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5

In [218]:
w, b

(tensor([[ 0.7726, -0.1006,  0.4106],
         [-0.5274,  1.8564, -0.2429]], requires_grad=True),
 tensor([1.1266, 0.6159], requires_grad=True))

In [219]:
loss = mse(model(inputs), targets)
loss

tensor(1107.8596, grad_fn=<DivBackward0>)

# Steps to train model using gradient descent

1. Generate prediction
2. Calculate Loss
3. Compute gradient w.r.t. the weights and biases
4. Adjust the weight by subtracting a small quantity proportional to the gradient
5. Reset the gradient to zero



In [248]:
preds = model(inputs)
preds

tensor([[ 64.2379, 113.0109],
        [ 83.5494, 148.9533],
        [ 74.0369, 245.7579],
        [ 84.7477,  55.3760],
        [ 69.5146, 171.4496]], grad_fn=<AddBackward0>)

In [249]:
loss = mse(preds, targets)
loss

tensor(2710.7017, grad_fn=<DivBackward0>)

In [250]:
loss.backward()
w.grad, b.grad

(tensor([[  202.2683, -1153.0433,  -422.5566],
         [ 4561.3701,  5607.3018,  3161.9641]]),
 tensor([-0.9827, 54.9095]))

In [251]:
with torch.no_grad():
  w -= w.grad * 1e-5
  b -= b.grad * 1e-5

  w.grad.zero_()
  b.grad.zero_()

In [252]:
# check new weights and biases

In [253]:
w, b

(tensor([[ 0.7115, -0.0810,  0.4047],
         [-0.3439,  2.0096, -0.1301]], requires_grad=True),
 tensor([1.1261, 0.6181], requires_grad=True))

In [254]:
preds = model(inputs)
loss = mse(preds, targets)
loss

tensor(2128.8840, grad_fn=<DivBackward0>)

# Train for 100 epochs

In [312]:
for i in range(100):
  preds = model(inputs)
  loss = mse(preds, targets)
  loss.backward()
  with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [313]:
preds = model(inputs)
loss = mse(preds, targets)
loss

tensor(0.9408, grad_fn=<DivBackward0>)

# Built-in fnc for Linear Regresion

In [320]:
import numpy as np

# Inputs (15 samples, 3 features each: temp, rainfall, humidity)
np_inputs = np.array([
    [73, 67, 43],
    [91, 88, 64],
    [87, 134, 58],
    [102, 43, 37],
    [69, 96, 70],
    [74, 66, 43],
    [91, 87, 65],
    [88, 134, 59],
    [101, 44, 37],
    [68, 96, 71],
    [73, 66, 44],
    [92, 87, 64],
    [87, 135, 57],
    [103, 43, 36],
    [68, 97, 70]
], dtype='float32')

# Targets (apples, oranges)
np_targets = np.array([
    [56, 70],
    [81, 101],
    [119, 133],
    [22, 37],
    [103, 119],
    [57, 69],
    [80, 102],
    [118, 132],
    [21, 38],
    [104, 118],
    [57, 69],
    [82, 100],
    [118, 134],
    [20, 38],
    [102, 120]
], dtype='float32')

inputs = torch.from_numpy(np_inputs)
targets = torch.from_numpy(np_targets)

In [325]:
# define dataset
train_ds = TensorDataset(inputs, targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [328]:
# define dataloader

In [329]:
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)

In [330]:
for xb, yb in train_dl:
  print(xb)
  print(yb)
  break

tensor([[ 88., 134.,  59.],
        [103.,  43.,  36.],
        [ 87., 134.,  58.],
        [ 68.,  97.,  70.],
        [ 69.,  96.,  70.]])
tensor([[118., 132.],
        [ 20.,  38.],
        [119., 133.],
        [102., 120.],
        [103., 119.]])


# PREDEFINED FUCNTION OR LINERA REGRESSION IN PYROTCH

In [333]:
model = nn.Linear(3, 2)
model.weight, model.bias

(Parameter containing:
 tensor([[-0.3349, -0.3211,  0.1868],
         [-0.3896,  0.0767, -0.2071]], requires_grad=True),
 Parameter containing:
 tensor([-0.5023,  0.4322], requires_grad=True))

In [334]:
list(model.parameters())

[Parameter containing:
 tensor([[-0.3349, -0.3211,  0.1868],
         [-0.3896,  0.0767, -0.2071]], requires_grad=True),
 Parameter containing:
 tensor([-0.5023,  0.4322], requires_grad=True)]

In [336]:
preds = model(inputs)
preds

tensor([[-38.4313, -31.7745],
        [-47.2799, -41.5251],
        [-61.8334, -35.1957],
        [-41.5562, -43.6722],
        [-41.3609, -33.5820],
        [-38.4450, -32.2408],
        [-46.7719, -41.8088],
        [-61.9815, -35.7924],
        [-41.5425, -43.2059],
        [-40.8392, -33.3994],
        [-37.9234, -32.0583],
        [-47.2936, -41.9914],
        [-62.3414, -34.9120],
        [-42.0779, -43.8548],
        [-41.3471, -33.1157]], grad_fn=<AddmmBackward0>)

In [341]:
# define loss from nn.functional library of pytorch
loss_fn = f.mse_loss

In [343]:
loss = loss_fn(preds, targets)
loss

tensor(17149.0527, grad_fn=<MseLossBackward0>)

In [345]:
# define optimizer from SGD (Stocastic Gradient Descent) package
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

# Step to train model

1. Genetate Prediction
2. Calculate loss
3. compute gradient wrt to the weights and the biases
4. adjust the weights by substracting s small quantity proportional to the gradient
5. reset the gradient to zero

In [346]:
# uitility function to train the model
def fit(num_epoches, model, loss_fn, opt, train_dl):

  #repeat for given number of epoch
  for epoch in range(num_epoches):

    # train with batches of data
    for xb, yb in train_dl:

      # 1. generate prediction
      pred = model(xb)

      # 2. calculate the loss
      loss = loss_fn(pred, yb)

      # 3. calculate gradient
      loss.backward()

      # 4. adjust the weights wrt to the small quantity proportional to the gradient
      opt.step()

      # 5. reset the gradients to zero
      opt.zero_grad()

    if (epoch+1) % 10 == 0 :
      print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epoches, loss.item()))

In [347]:
fit(100, model, loss_fn, opt, train_dl)

Epoch [10/100], Loss: 204.1078
Epoch [20/100], Loss: 247.0152
Epoch [30/100], Loss: 119.5961
Epoch [40/100], Loss: 118.1157
Epoch [50/100], Loss: 88.5077
Epoch [60/100], Loss: 45.8165
Epoch [70/100], Loss: 36.9879
Epoch [80/100], Loss: 31.7929
Epoch [90/100], Loss: 22.3566
Epoch [100/100], Loss: 14.3985


In [348]:
pred = model(inputs)
pred

tensor([[ 57.8001,  71.3663],
        [ 82.4557,  97.2539],
        [115.5459, 138.4521],
        [ 26.4771,  42.7773],
        [ 99.2189, 109.9603],
        [ 56.7210,  70.3025],
        [ 82.3306,  96.7205],
        [115.8986, 138.7294],
        [ 27.5562,  43.8411],
        [100.1730, 110.4908],
        [ 57.6751,  70.8330],
        [ 81.3765,  96.1900],
        [115.6710, 138.9854],
        [ 25.5230,  42.2468],
        [100.2980, 111.0241]], grad_fn=<AddmmBackward0>)

In [349]:
model(torch.tensor([[75,63,44.]]))

tensor([[54.7384, 67.7680]], grad_fn=<AddmmBackward0>)