<a href="https://colab.research.google.com/github/rautaditya2606/deep-learning-cv-by-jovian/blob/main/Zero_to_GANs_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [140]:
import torch

In [141]:
t1 = torch.tensor(3.)
t1, t1.dtype

(tensor(3.), torch.float32)

In [142]:
t2 = torch.tensor([[[1.,2.,3.],
                    [4.,5.,6.],
                    [7.,8.,9.]]])

In [143]:
t2, t2.dtype

(tensor([[[1., 2., 3.],
          [4., 5., 6.],
          [7., 8., 9.]]]),
 torch.float32)

In [144]:
t2.shape

torch.Size([1, 3, 3])

In [145]:
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)

In [146]:
y = w * x + b
y

tensor(17., grad_fn=<AddBackward0>)

In [147]:
# computes derivatives
y.backward()

In [148]:
#display derivatives
print('dy/dx', x.grad)
print('dy/dw', w.grad)
print('dy/db', b.grad)

dy/dx None
dy/dw tensor(3.)
dy/db tensor(1.)


In [149]:
t6 = torch.full([1,3,3], 18)
t6

tensor([[[18, 18, 18],
         [18, 18, 18],
         [18, 18, 18]]])

In [150]:
t7 = torch.cat((t2, t6))
t7, t7.shape

(tensor([[[ 1.,  2.,  3.],
          [ 4.,  5.,  6.],
          [ 7.,  8.,  9.]],
 
         [[18., 18., 18.],
          [18., 18., 18.],
          [18., 18., 18.]]]),
 torch.Size([2, 3, 3]))

In [151]:
t8 = torch.sin(t7)
t8

tensor([[[ 0.8415,  0.9093,  0.1411],
         [-0.7568, -0.9589, -0.2794],
         [ 0.6570,  0.9894,  0.4121]],

        [[-0.7510, -0.7510, -0.7510],
         [-0.7510, -0.7510, -0.7510],
         [-0.7510, -0.7510, -0.7510]]])

In [152]:
t9 = t7.reshape(3,3,2)
t9

tensor([[[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.]],

        [[ 7.,  8.],
         [ 9., 18.],
         [18., 18.]],

        [[18., 18.],
         [18., 18.],
         [18., 18.]]])

In [153]:
# integration of numpy and pytorch

In [154]:
import numpy as np

x = np.array([[1.,2.],
              [3.,4.]])
x, x.dtype

(array([[1., 2.],
        [3., 4.]]),
 dtype('float64'))

In [155]:
y = torch.from_numpy(x).type(torch.float32)
y, y.dtype

(tensor([[1., 2.],
         [3., 4.]]),
 torch.float32)

In [156]:
# linear regression model

In [157]:
# inputs (temp, rainfall ,humidity)
num_inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70]])

In [158]:
num_targets = np.array([[56,70],
                    [81,101],
                    [119, 133],
                    [22, 37],
                    [103, 119]], dtype='float32')

In [189]:
# convert np array to torch tensor
inputs = torch.from_numpy(num_inputs)
targets = torch.from_numpy(num_targets)

In [190]:
inputs = inputs.type(torch.float32)
targets = targets.type(torch.float32)

In [191]:
w = torch.randn(2, 3, requires_grad=True)
b = torch.randn(2, requires_grad = True)
w, b

(tensor([[ 0.9097, -0.0416,  0.4657],
         [-1.4288,  0.9336, -0.8311]], requires_grad=True),
 tensor([1.1280, 0.6053], requires_grad=True))

In [192]:
inputs

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])

In [193]:
inputs @ w.T + b

tensor([[  84.7705,  -76.8813],
        [ 110.0502, -100.4466],
        [ 101.7019,  -46.7980],
        [ 109.3565, -135.7370],
        [  92.4982,  -66.5305]], grad_fn=<AddBackward0>)

In [194]:
def model(x):
  return x @ w.T + b

In [195]:
preds = model(inputs)
preds

tensor([[  84.7705,  -76.8813],
        [ 110.0502, -100.4466],
        [ 101.7019,  -46.7980],
        [ 109.3565, -135.7370],
        [  92.4982,  -66.5305]], grad_fn=<AddBackward0>)

In [196]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [197]:
def mse(preds, targets):
  diff = preds - targets
  return torch.sum(diff * diff) / diff.numel()

In [198]:
loss = mse(preds, targets)

In [199]:
# compute gradient
loss.backward()

In [200]:
w, w.grad

(tensor([[ 0.9097, -0.0416,  0.4657],
         [-1.4288,  0.9336, -0.8311]], requires_grad=True),
 tensor([[  2284.9226,    982.8491,    918.0232],
         [-15023.4365, -15379.9805,  -9803.0342]]))

In [201]:
b, b.grad

(tensor([1.1280, 0.6053], requires_grad=True), tensor([  23.4754, -177.2787]))

In [217]:
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5

In [218]:
w, b

(tensor([[ 0.7726, -0.1006,  0.4106],
         [-0.5274,  1.8564, -0.2429]], requires_grad=True),
 tensor([1.1266, 0.6159], requires_grad=True))

In [219]:
loss = mse(model(inputs), targets)
loss

tensor(1107.8596, grad_fn=<DivBackward0>)

# Steps to train model using gradient descent

1. Generate prediction
2. Calculate Loss
3. Compute gradient w.r.t. the weights and biases
4. Adjust the weight by subtracting a small quantity proportional to the gradient
5. Reset the gradient to zero



In [248]:
preds = model(inputs)
preds

tensor([[ 64.2379, 113.0109],
        [ 83.5494, 148.9533],
        [ 74.0369, 245.7579],
        [ 84.7477,  55.3760],
        [ 69.5146, 171.4496]], grad_fn=<AddBackward0>)

In [249]:
loss = mse(preds, targets)
loss

tensor(2710.7017, grad_fn=<DivBackward0>)

In [250]:
loss.backward()
w.grad, b.grad

(tensor([[  202.2683, -1153.0433,  -422.5566],
         [ 4561.3701,  5607.3018,  3161.9641]]),
 tensor([-0.9827, 54.9095]))

In [251]:
with torch.no_grad():
  w -= w.grad * 1e-5
  b -= b.grad * 1e-5

  w.grad.zero_()
  b.grad.zero_()

In [252]:
# check new weights and biases

In [253]:
w, b

(tensor([[ 0.7115, -0.0810,  0.4047],
         [-0.3439,  2.0096, -0.1301]], requires_grad=True),
 tensor([1.1261, 0.6181], requires_grad=True))

In [254]:
preds = model(inputs)
loss = mse(preds, targets)
loss

tensor(2128.8840, grad_fn=<DivBackward0>)

# Train for 100 epochs

In [312]:
for i in range(100):
  preds = model(inputs)
  loss = mse(preds, targets)
  loss.backward()
  with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [313]:
preds = model(inputs)
loss = mse(preds, targets)
loss

tensor(0.9408, grad_fn=<DivBackward0>)